// src/routes/settings/ExerciseDatabase.svelte
<script lang="ts">
  import { Activity } from 'lucide-svelte'
  import { getExerciseKey } from '../../utils'
  import { blockTemplates } from '../../blockTemplates'
  import { exerciseStore, preferencesStore, trainingPlanStore } from '../../stores'
  
  // Access stores directly using $derived for reactive values
  const exerciseState = $derived($exerciseStore)
  const maxes = $derived(exerciseState.maxes)
  const tenRMs = $derived(exerciseState.tenRMs)
  const weightUnit = $derived($preferencesStore.weightUnit)
  const customPlan = $derived($trainingPlanStore.customPlan)
  const currentBlockName = $derived(customPlan[0]?.name || 'No active block')
  
  // Update functions for direct store updates
  const updateMax = (exerciseKey: string, value: number) => {
    exerciseStore.update(state => ({
      ...state,
      maxes: { ...state.maxes, [exerciseKey]: value }
    }))
  }
  
  const updateTenRM = (exerciseKey: string, value: number) => {
    exerciseStore.update(state => ({
      ...state,
      tenRMs: { ...state.tenRMs, [exerciseKey]: value }
    }))
  }

  // Extract function outside reactive context - better performance
  const getCurrentBlockExercises = () => {
    const currentBlock = customPlan[0]
    if (!currentBlock) return { strengthExercises: [], hypertrophyExercises: [] }
    
    const blockTemplate = blockTemplates[currentBlock.type as keyof typeof blockTemplates]
    if (!blockTemplate) return { strengthExercises: [], hypertrophyExercises: [] }
    
    const strengthExercises = new Set<string>()
    const hypertrophyExercises = new Set<string>()
    
    blockTemplate.weeks.forEach((week: { days: unknown[] }) => {
      week.days.forEach((day: unknown) => {
        const dayObj = day as Record<string, unknown>
        if ('exercises' in dayObj && Array.isArray(dayObj.exercises)) {
          (dayObj.exercises as string[]).forEach((exercise: string) => {
            if (dayObj.type === 'strength') {
              strengthExercises.add(exercise)
            } else if (dayObj.type === 'hypertrophy') {
              hypertrophyExercises.add(exercise)
            }
          })
        }
      })
    })
    
    return {
      strengthExercises: Array.from(strengthExercises),
      hypertrophyExercises: Array.from(hypertrophyExercises)
    }
  }

  // More idiomatic derived values - calculate once when dependencies change
  const exerciseData = $derived(getCurrentBlockExercises())
  const strengthExercises = $derived(exerciseData.strengthExercises)
  const hypertrophyExercises = $derived(exerciseData.hypertrophyExercises)
</script>

<div class="mb-6">
  <h3 class="text-lg font-semibold mb-4">Exercise Database - {currentBlockName}</h3>
  <div class="text-sm text-gray-600 mb-4">
    Showing exercises for your current block. Values update automatically for weight calculations.
  </div>
  
  {#if strengthExercises.length > 0}
    <div class="mb-6">
      <h4 class="text-md font-semibold text-gray-800 mb-3 flex items-center gap-2">
        <span class="w-3 h-3 bg-red-500 rounded-full"></span>
        Strength Exercises (1RM - {weightUnit})
      </h4>
      <div class="space-y-3">
        {#each strengthExercises as exercise}
          {@const exerciseKey = getExerciseKey(exercise)}
          
          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3">
            <label for="max-{exerciseKey}" class="flex-1 text-sm text-gray-700 font-medium">{exercise}</label>
            <div class="flex items-center gap-2">
              <input
                id="max-{exerciseKey}"
                type="number"
                value={maxes[exerciseKey] || ''}
                oninput={(e) => {
                  const target = e.target as HTMLInputElement
                  const value = parseFloat(target.value) || 0
                  updateMax(exerciseKey, value)
                }}
                class="w-24 p-2 border-2 border-gray-300 rounded-lg text-sm font-medium focus:border-red-500 focus:ring-2 focus:ring-red-200 transition-all"
                placeholder="1RM"
                step={weightUnit === 'kg' ? '2.5' : '5'}
              />
              <span class="text-xs text-gray-500 font-medium w-8">{weightUnit}</span>
            </div>
          </div>
        {/each}
      </div>
    </div>
  {/if}

  {#if hypertrophyExercises.length > 0}
    <div class="mb-6">
      <h4 class="text-md font-semibold text-gray-800 mb-3 flex items-center gap-2">
        <span class="w-3 h-3 bg-blue-500 rounded-full"></span>
        Hypertrophy Exercises (10RM - {weightUnit})
      </h4>
      <div class="space-y-3">
        {#each hypertrophyExercises as exercise}
          {@const exerciseKey = getExerciseKey(exercise)}
          
          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3">
            <label for="tenrm-{exerciseKey}" class="flex-1 text-sm text-gray-700 font-medium">{exercise}</label>
            <div class="flex items-center gap-2">
              <input
                id="tenrm-{exerciseKey}"
                type="number"
                value={tenRMs[exerciseKey] || ''}
                oninput={(e) => {
                  const target = e.target as HTMLInputElement
                  const value = parseFloat(target.value) || 0
                  updateTenRM(exerciseKey, value)
                }}
                class="w-24 p-2 border-2 border-gray-300 rounded-lg text-sm font-medium focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all"
                placeholder="10RM"
                step="1"
              />
              <span class="text-xs text-gray-500 font-medium w-8">{weightUnit}</span>
            </div>
          </div>
        {/each}
      </div>
    </div>
  {/if}

  {#if strengthExercises.length === 0 && hypertrophyExercises.length === 0}
    <div class="text-center text-gray-400 py-8">
      <Activity class="w-12 h-12 mx-auto mb-3 opacity-50" />
      <p>No resistance exercises in current block</p>
      <p class="text-xs mt-1">Switch to a strength or powerbuilding block to see exercise settings</p>
    </div>
  {/if}
</div>

// src/components/ExerciseDatabase.tsx
import React from 'react';
import { Activity } from 'lucide-react';
import type { AppState } from '../types';
import { getExerciseKey } from '../utils';

interface ExerciseDatabaseProps {
  state: AppState;
  strengthExercises: string[];
  hypertrophyExercises: string[];
  currentBlockName: string;
  onUpdateState: (updates: Partial<AppState>) => void;
}

const ExerciseDatabase: React.FC<ExerciseDatabaseProps> = ({
  state,
  strengthExercises,
  hypertrophyExercises,
  currentBlockName,
  onUpdateState
}) => {
  return (
    <div className="mb-6">
      <h3 className="text-lg font-semibold mb-4">Exercise Database - {currentBlockName}</h3>
      <div className="text-sm text-gray-600 mb-4">
        Showing exercises for your current block. Values update automatically for weight calculations.
      </div>
      
      {strengthExercises.length > 0 && (
        <div className="mb-6">
          <h4 className="text-md font-semibold text-gray-800 mb-3 flex items-center gap-2">
            <span className="w-3 h-3 bg-red-500 rounded-full"></span>
            Strength Exercises (1RM - {state.weightUnit})
          </h4>
          <div className="space-y-3">
            {strengthExercises.map((exercise: string) => {
              const exerciseKey = getExerciseKey(exercise);
              
              return (
                <div key={exerciseKey} className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3">
                  <label className="flex-1 text-sm text-gray-700 font-medium">{exercise}</label>
                  <div className="flex items-center gap-2">
                    <input
                      type="number"
                      value={state.maxes[exerciseKey] || ''}
                      onChange={(e) => onUpdateState({ 
                        maxes: { ...state.maxes, [exerciseKey]: parseFloat(e.target.value) || 0 }
                      })}
                      className="w-24 p-2 border-2 border-gray-300 rounded-lg text-sm font-medium focus:border-red-500 focus:ring-2 focus:ring-red-200 transition-all"
                      placeholder="1RM"
                      step={state.weightUnit === 'kg' ? '2.5' : '5'}
                    />
                    <span className="text-xs text-gray-500 font-medium w-8">{state.weightUnit}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {hypertrophyExercises.length > 0 && (
        <div className="mb-6">
          <h4 className="text-md font-semibold text-gray-800 mb-3 flex items-center gap-2">
            <span className="w-3 h-3 bg-blue-500 rounded-full"></span>
            Hypertrophy Exercises (10RM - {state.weightUnit})
          </h4>
          <div className="space-y-3">
            {hypertrophyExercises.map((exercise: string) => {
              const exerciseKey = getExerciseKey(exercise);
              
              return (
                <div key={exerciseKey} className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3">
                  <label className="flex-1 text-sm text-gray-700 font-medium">{exercise}</label>
                  <div className="flex items-center gap-2">
                    <input
                      type="number"
                      value={state.tenRMs[exerciseKey] || ''}
                      onChange={(e) => onUpdateState({ 
                        tenRMs: { ...state.tenRMs, [exerciseKey]: parseFloat(e.target.value) || 0 }
                      })}
                      className="w-24 p-2 border-2 border-gray-300 rounded-lg text-sm font-medium focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all"
                      placeholder="10RM"
                      step="1"
                    />
                    <span className="text-xs text-gray-500 font-medium w-8">{state.weightUnit}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {strengthExercises.length === 0 && hypertrophyExercises.length === 0 && (
        <div className="text-center text-gray-400 py-8">
          <Activity className="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p>No resistance exercises in current block</p>
          <p className="text-xs mt-1">Switch to a strength or powerbuilding block to see exercise settings</p>
        </div>
      )}
    </div>
  );
};

export default ExerciseDatabase;
