// src/routes/workout/StrengthWorkouts.svelte
<script lang="ts">
  import { CheckCircle } from 'lucide-svelte'
  import { workoutStore, exerciseStore, preferencesStore } from '$lib/stores'
  import RestTimer from './RestTimer.svelte'
  import type { 
    Workout, 
    StrengthWorkout, 
    HypertrophyWorkout
  } from '$lib/types'
  import { 
    calculateWeight, 
    calculateHypertrophyWeight, 
    calculateWarmupSets,
    requestNotificationPermission
  } from '$lib/utils'

  interface StrengthWorkoutsProps {
    workout: Workout
    onCompleteWorkout: () => void
  }

  let { workout, onCompleteWorkout }: StrengthWorkoutsProps = $props()
  
  // Access stores directly
  const completedSets = $derived($workoutStore.completedSets)
  const maxes = $derived($exerciseStore.maxes)
  const tenRMs = $derived($exerciseStore.tenRMs)
  const weightUnit = $derived($preferencesStore.weightUnit)

  // Local rest timer state using runes
  let restTimer = $state({
    isActive: false,
    timeLeft: 0,
    totalTime: 0,
    workoutType: null as 'strength' | 'hypertrophy' | null,
    phase: 'initial' as 'initial' | 'extended',
    startTime: 0
  })

  // Rest timer update function
  const updateRestTimer = (updates: Partial<typeof restTimer>) => {
    Object.assign(restTimer, updates)
  }

  // Stop rest timer function
  const stopRestTimer = () => {
    restTimer.isActive = false
    restTimer.timeLeft = 0
    restTimer.totalTime = 0
    restTimer.workoutType = null
    restTimer.phase = 'initial'
    restTimer.startTime = 0
  }

  const toggleSet = async (exerciseAndSchemeIndex: string, setIndex: number) => {
    const key = `${exerciseAndSchemeIndex}-${setIndex}`
    const isBeingCompleted = !completedSets[key]
    
    // Update completed sets in store
    workoutStore.update(state => ({
      ...state,
      completedSets: {
        ...state.completedSets,
        [key]: isBeingCompleted
      }
    }))
    
    // Start rest timer when completing a working set (not warm-up sets)
    if (isBeingCompleted && !key.includes('warmup')) {
      if (workout && (workout.type === 'strength' || workout.type === 'hypertrophy')) {
        // Request notification permission without blocking (don't await)
        requestNotificationPermission()
        
        const initialTime = workout.type === 'strength' ? 180 : 90 // 3 min for strength, 1.5 min for hypertrophy
        const now = Date.now()
        
        // Update local rest timer state
        restTimer.isActive = true
        restTimer.timeLeft = initialTime
        restTimer.totalTime = initialTime
        restTimer.workoutType = workout.type as 'strength' | 'hypertrophy'
        restTimer.phase = 'initial'
        restTimer.startTime = now
      }
    }
  }

  // Derive strength workout with proper typing - more idiomatic than casting everywhere
  const strengthWorkout = $derived(() => workout as StrengthWorkout | HypertrophyWorkout)

  // Extract helper functions outside reactive context - they don't need to be reactive
  const getExerciseData = (exerciseIndex: number, schemeIndex: number) => {
    const setSchemes = (strengthWorkout().sets || '').split(',')
    const intensities = String(strengthWorkout().intensity || 0).split(',')
    const shouldMapByIndex = setSchemes.length === (strengthWorkout().exercises || []).length
    
    const intensityIndex = shouldMapByIndex ? exerciseIndex : schemeIndex
    const intensity = parseInt(intensities[intensityIndex] || intensities[0])
    
    return { intensity, shouldMapByIndex }
  }

  const isSetCompleted = (key: string) => Boolean(completedSets[key])
</script>

{#if workout.type === 'strength' || workout.type === 'hypertrophy'}
  <div class="space-y-4">
    <RestTimer 
      isActive={restTimer.isActive}
      timeLeft={restTimer.timeLeft}
      totalTime={restTimer.totalTime}
      workoutType={restTimer.workoutType}
      phase={restTimer.phase}
      startTime={restTimer.startTime}
      onUpdate={updateRestTimer}
      onStop={stopRestTimer}
    />
    {#each (strengthWorkout().exercises || []) as exercise, exerciseIndex}
      {@const setSchemes = (strengthWorkout().sets || '').split(',')}
      {@const exerciseSetSchemes = getExerciseData(exerciseIndex, 0).shouldMapByIndex ? [setSchemes[exerciseIndex]] : setSchemes}
      
      {#each exerciseSetSchemes as setScheme, schemeIndex}
        {@const { intensity } = getExerciseData(exerciseIndex, schemeIndex)}
        {@const weight = strengthWorkout().type === 'strength' ? 
          calculateWeight(exercise, intensity, { maxes, weightUnit }) : 
          calculateHypertrophyWeight(exercise, intensity, { tenRMs, maxes })}
        {@const [sets, reps] = setScheme.split('x')}
        {@const warmupSets = strengthWorkout().type === 'strength' && weight > 0 ? calculateWarmupSets(exercise, weight, { weightUnit }) : []}
        
        <div class="bg-gray-50 rounded-xl p-5 border border-gray-200">
          <h4 class="font-bold text-gray-900 mb-2 text-lg">{exercise}</h4>
          <div class="text-sm text-gray-600 mb-4 font-medium">
            {setScheme} @ {intensity}%{weight > 0 ? ` (${weight} ${weightUnit})` : ''}
          </div>
          
          {#if warmupSets.length > 0}
            <div class="mb-4">
              <h5 class="text-sm font-semibold text-gray-700 mb-2">Warm-up Sets</h5>
              <div class="space-y-2">
                {#each warmupSets as warmupSet, warmupIndex}
                  {@const warmupKey = `warmup-${exerciseIndex}-${schemeIndex}-${warmupIndex}-0`}
                  
                  <div class="flex items-center justify-between bg-blue-50 p-3 rounded-lg border border-blue-200">
                    <div class="flex items-center gap-3">
                      <span class="text-xs font-medium text-blue-700 w-16">Warm-up {warmupIndex + 1}</span>
                      <span class="text-sm text-blue-800">{warmupSet.reps} reps @ {warmupSet.weight} {weightUnit}</span>
                    </div>
                    <button
                      onclick={() => toggleSet(`warmup-${exerciseIndex}-${schemeIndex}-${warmupIndex}`, 0)}
                      class="w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all {
                        isSetCompleted(warmupKey)
                          ? 'bg-blue-500 border-blue-500 text-white' : 'border-blue-300 hover:border-blue-400 bg-white'
                      }"
                    >
                      {#if isSetCompleted(warmupKey)}
                        <CheckCircle class="w-4 h-4" />
                      {/if}
                    </button>
                  </div>
                {/each}
              </div>
            </div>
          {/if}
          
          <div class="space-y-3">
            <h5 class="text-sm font-semibold text-gray-700">Working Sets</h5>
            {#each Array(parseInt(sets)) as _, setIndex}
              {@const setKey = `${exerciseIndex}-${schemeIndex}-${setIndex}`}
              
              <div class="flex items-center justify-between bg-white p-4 rounded-lg border-2 border-gray-200 hover:border-gray-300 transition-all">
                <div class="flex items-center gap-3">
                  <span class="text-sm font-semibold text-gray-700 w-12">Set {setIndex + 1}</span>
                  <span class="text-sm text-gray-800">{reps} reps</span>
                </div>
                <div class="flex items-center gap-3">
                  {#if weight > 0}
                    <input
                      type="number"
                      class="w-20 px-3 py-2 border-2 border-gray-300 rounded-lg text-sm font-medium focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all"
                      value={weight}
                      placeholder="Weight"
                      step={weightUnit === 'kg' ? '2.5' : '5'}
                    />
                  {/if}
                  <button
                    onclick={() => toggleSet(`${exerciseIndex}-${schemeIndex}`, setIndex)}
                    class="w-8 h-8 rounded-full border-2 flex items-center justify-center transition-all {
                      isSetCompleted(setKey)
                        ? 'bg-green-500 border-green-500 text-white' : 'border-gray-300 hover:border-green-400 bg-white'
                    }"
                  >
                    {#if isSetCompleted(setKey)}
                      <CheckCircle class="w-5 h-5" />
                    {/if}
                  </button>
                </div>
              </div>
            {/each}
          </div>
        </div>
      {/each}
    {/each}
    
    <button 
      onclick={onCompleteWorkout} 
      class="w-full bg-green-500 hover:bg-green-600 text-white font-semibold py-3 rounded-lg transition-colors"
    >
      Complete Workout
    </button>
  </div>
{/if}

// src/components/StrengthWorkouts.tsx
import React, { useEffect } from 'react';
import { Clock, CheckCircle } from 'lucide-react';
import type { 
  Workout, 
  StrengthWorkout, 
  HypertrophyWorkout, 
  AppState 
} from '../types';
import { 
  calculateWeight, 
  calculateHypertrophyWeight, 
  calculateWarmupSets, 
  showRestCompleteNotification
} from '../utils';

interface StrengthWorkoutsProps {
  workout: Workout;
  state: AppState;
  onCompleteWorkout: () => void;
  onToggleSet: (exerciseAndSchemeIndex: string, setIndex: number) => Promise<void>;
  onUpdateState: (updates: Partial<AppState>) => void;
}

const StrengthWorkouts: React.FC<StrengthWorkoutsProps> = ({
  workout,
  state,
  onCompleteWorkout,
  onToggleSet,
  onUpdateState
}) => {
  // Timer effect - timestamp-based to prevent background throttling
  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    
    if (state.restTimer.isActive && state.restTimer.timeLeft > 0) {
      interval = setInterval(() => {
        const now = Date.now();
        const elapsedSeconds = Math.floor((now - state.restTimer.startTime) / 1000);
        const newTimeLeft = Math.max(0, state.restTimer.totalTime - elapsedSeconds);
        
        onUpdateState({
          restTimer: {
            ...state.restTimer,
            timeLeft: newTimeLeft
          }
        });
      }, 100); // Check more frequently for smoother updates
    }

    return () => {
      if (interval) clearInterval(interval);
    };
  }, [state.restTimer, onUpdateState]);

  // Separate effect to handle notification when timer reaches 0
  useEffect(() => {
    if (state.restTimer.isActive && state.restTimer.timeLeft === 0) {
      showRestCompleteNotification();
    }
  }, [state.restTimer.timeLeft, state.restTimer.isActive]);

  if (workout.type !== 'strength' && workout.type !== 'hypertrophy') {
    return null;
  }

  const strengthWorkout = workout as StrengthWorkout | HypertrophyWorkout;

  // Timer functions
  const stopRestTimer = () => {
    onUpdateState({
      restTimer: {
        isActive: false,
        timeLeft: 0,
        totalTime: 0,
        workoutType: null,
        phase: 'initial',
        startTime: 0
      }
    });
  };

  const extendRestTimer = () => {
    if (state.restTimer.workoutType === 'strength' && state.restTimer.phase === 'initial') {
      const extendedTime = 120; // Additional 2 minutes to reach 5 minutes total
      const now = Date.now();
      onUpdateState({
        restTimer: {
          ...state.restTimer,
          timeLeft: extendedTime,
          totalTime: extendedTime,
          phase: 'extended',
          startTime: now
        }
      });
    }
  };

  const renderRestTimer = () => {
    if (!state.restTimer.isActive) return null;

    const progressPercent = ((state.restTimer.totalTime - state.restTimer.timeLeft) / state.restTimer.totalTime) * 100;
    const isExtendedPhase = state.restTimer.phase === 'extended';
    const minutes = Math.floor(state.restTimer.timeLeft / 60);
    const seconds = state.restTimer.timeLeft % 60;
    
    return (
      <div className="mb-4 p-4 bg-white rounded-lg border-2 border-orange-200">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <Clock className="w-5 h-5 text-orange-600" />
            <span className="text-sm font-semibold text-gray-700">
              {isExtendedPhase ? 'Extended Rest' : 'Rest Time'}
            </span>
          </div>
          <div className="text-lg font-bold text-gray-900">
            {minutes}:{seconds.toString().padStart(2, '0')}
          </div>
        </div>
        
        <div className="mb-3">
          <div className="bg-gray-200 h-3 rounded-full overflow-hidden">
            <div 
              className={`h-full transition-all duration-300 ${
                isExtendedPhase ? 'bg-red-500' : 'bg-orange-500'
              }`}
              style={{ width: `${progressPercent}%` }}
            />
          </div>
        </div>
        
        <div className="flex gap-2">
          <button
            onClick={stopRestTimer}
            className={`flex-1 ${
              state.restTimer.timeLeft === 0 
                ? 'bg-green-500 hover:bg-green-600' 
                : 'bg-gray-500 hover:bg-gray-600'
            } text-white font-medium py-2 px-4 rounded-lg transition-colors text-sm`}
          >
            {state.restTimer.timeLeft === 0 ? 'Complete Rest' : 'Skip Rest'}
          </button>
          {state.restTimer.workoutType === 'strength' && !isExtendedPhase && state.restTimer.timeLeft === 0 && (
            <button
              onClick={extendRestTimer}
              className="flex-1 bg-red-500 hover:bg-red-600 text-white font-medium py-2 px-4 rounded-lg transition-colors text-sm"
            >
              Extend to 5 min
            </button>
          )}
        </div>
      </div>
    );
  };

  const renderExerciseSet = (
    exercise: string, 
    exerciseIndex: number, 
    setScheme: string, 
    schemeIndex: number, 
    intensity: number, 
    weight: number, 
    workout: StrengthWorkout | HypertrophyWorkout
  ) => {
    const [sets, reps] = setScheme.split('x');
    const warmupSets = workout.type === 'strength' && weight > 0 ? calculateWarmupSets(exercise, weight, state) : [];
    
    return (
      <div key={`${exerciseIndex}-${schemeIndex}`} className="bg-gray-50 rounded-xl p-5 border border-gray-200">
        <h4 className="font-bold text-gray-900 mb-2 text-lg">{exercise}</h4>
        <div className="text-sm text-gray-600 mb-4 font-medium">
          {setScheme} @ {intensity}%{weight > 0 && ` (${weight} ${state.weightUnit})`}
        </div>
        
        {warmupSets.length > 0 && (
          <div className="mb-4">
            <h5 className="text-sm font-semibold text-gray-700 mb-2">Warm-up Sets</h5>
            <div className="space-y-2">
              {warmupSets.map((warmupSet, warmupIndex) => (
                <div key={`warmup-${warmupIndex}`} className="flex items-center justify-between bg-blue-50 p-3 rounded-lg border border-blue-200">
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-medium text-blue-700 w-16">Warm-up {warmupIndex + 1}</span>
                    <span className="text-sm text-blue-800">{warmupSet.reps} reps @ {warmupSet.weight} {state.weightUnit}</span>
                  </div>
                  <button
                    onClick={() => onToggleSet(`warmup-${exerciseIndex}-${schemeIndex}-${warmupIndex}`, 0)}
                    className={`w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all ${
                      state.completedSets[`warmup-${exerciseIndex}-${schemeIndex}-${warmupIndex}-0`]
                        ? 'bg-blue-500 border-blue-500 text-white' : 'border-blue-300 hover:border-blue-400 bg-white'
                    }`}
                  >
                    {state.completedSets[`warmup-${exerciseIndex}-${schemeIndex}-${warmupIndex}-0`] && <CheckCircle className="w-4 h-4" />}
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
        
        <div className="space-y-3">
          <h5 className="text-sm font-semibold text-gray-700">Working Sets</h5>
          {Array.from({ length: parseInt(sets) }).map((_, setIndex) => (
            <div key={setIndex} className="flex items-center justify-between bg-white p-4 rounded-lg border border-gray-200">
              <div className="flex items-center gap-4">
                <span className="text-sm font-semibold text-gray-700 w-14">Set {setIndex + 1}</span>
                <span className="text-sm font-medium text-gray-600">{reps} reps</span>
              </div>
              <div className="flex items-center gap-3">
                {weight > 0 && (
                  <input
                    type="number"
                    className="w-20 px-3 py-2 border-2 border-gray-300 rounded-lg text-sm font-medium focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all"
                    defaultValue={weight}
                    placeholder="Weight"
                    step={state.weightUnit === 'kg' ? '2.5' : '5'}
                  />
                )}
                <button
                  onClick={() => onToggleSet(`${exerciseIndex}-${schemeIndex}`, setIndex)}
                  className={`w-8 h-8 rounded-full border-2 flex items-center justify-center transition-all ${
                    state.completedSets[`${exerciseIndex}-${schemeIndex}-${setIndex}`]
                      ? 'bg-green-500 border-green-500 text-white' : 'border-gray-300 hover:border-green-400 bg-white'
                  }`}
                >
                  {state.completedSets[`${exerciseIndex}-${schemeIndex}-${setIndex}`] && <CheckCircle className="w-5 h-5" />}
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-4">
      {renderRestTimer()}
      {(strengthWorkout.exercises || []).map((exercise: string, exerciseIndex: number) => {
        const setSchemes = (strengthWorkout.sets || '').split(',');
        const intensities = String(strengthWorkout.intensity || 0).split(',');
        const shouldMapByIndex = setSchemes.length === (strengthWorkout.exercises || []).length;
        const exerciseSetSchemes = shouldMapByIndex ? [setSchemes[exerciseIndex]] : setSchemes;
        
        return exerciseSetSchemes.map((setScheme, schemeIndex) => {
          const intensityIndex = shouldMapByIndex ? exerciseIndex : schemeIndex;
          const intensity = parseInt(intensities[intensityIndex] || intensities[0]);
          const weight = strengthWorkout.type === 'strength' ? 
            calculateWeight(exercise, intensity, state) : 
            calculateHypertrophyWeight(exercise, intensity, state);
          
          return renderExerciseSet(exercise, exerciseIndex, setScheme, schemeIndex, intensity, weight, strengthWorkout);
        });
      })}
      <button 
        onClick={onCompleteWorkout} 
        className="w-full bg-green-500 hover:bg-green-600 text-white font-semibold py-3 rounded-lg transition-colors"
      >
        Complete Workout
      </button>
    </div>
  );
};

export default StrengthWorkouts;
